### ISSUE TITLE
How to control LS-DYNA from python?

### ISSUE THREAD

**Issue by aivif** [lasso-gmbh/lasso-python#16]
Hi, I'm a newbie in python programming and LS-Dyna. In the closed issue from qd-cae-python (see link below) you wrote, that you can use python to start the ls-dyna solver. But how can you do this? I think this could help me, to solve my problem. Do you have some tips and info for me? Thank you!

[Can there any method to control LS-DYNA from python?](https://github.com/qd-cae/qd-cae-python/issues/64#issuecomment-575608922)

**Comment by tnt-codie** [comment]
You can do that by using the `subprocess.Popen` command. Simply hand it the required shell arguments to run the solver. The return value is a process handle. This process handle can be used for whatever you want, sending text input or even killing the process, See the documentation for [Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) for further infos.

Since this issue is not related to the codebase, I will close the ticket here.
