### ISSUE TITLE
Utilizing enum for ArrayType

### ISSUE THREAD

**Issue by CamelCMA** [lasso-gmbh/lasso-python#6]
Hello, using `enum` for `FilterType` is definitely a good idea.
I am thinking how to utilize `enum` for `ArrayType` as well.

### Issues I found
* We could do something like `ArrayType.node_displacement = "dummy_node_displacement "`, which seems not cool. 
* `get_state_array_names` works if (a) The name referenced here is the same as the ArrayType. (b) The returned items are really what we want.  These 2 actions are error-prone. 

#### Pros
By introducing `enum` and `property` :
* we can assign `enum =  (content, status_id)` at the same place.  `content` is serving as the api-call for user, and `status_id` is regarded as the filter for `get_state_array_names`, which returns the items if their `status_id` is set to `1`. 
* We can assure that the attribute can not be set. 

#### Cons
* the api-call needs to be changed from `ArrayType.node_displacement` to `ArrayType.node_displacement.content`.
*  Efforts must be taken to refactor the code.

#### Notes
* You can rename `content` and `status_id` whatever you feel more comfortable for api caller. Of course, you can extend the tuple if needed.
* I change `get_state_array_names` from `staticmethod` to `classmethod`, which sounds more appropriate from my perspective.
* `@enum.unique` helps us not assign the same value for enum accidentally.

### Concept code
```python
import typing
import enum


@enum.unique
class ArrayType(enum.Enum):
    """
    enum = (content, status_id)
    """
    global_timesteps = ("timesteps", 1)
    global_kinetic_energy = ("global_kinetic_energy", 1)
    airbag_variable_names = ("airbag_variable_names", 0) 


    def __new__(cls, content, status_id):
        member = object.__new__(cls)
        member._content = content
        member._status_id = status_id
        return member

    @property
    def content(self):
        return self._content

    @property
    def status_id(self):
        return self._status_id

    @classmethod
    def get_state_array_names(cls, status_id=1) -> typing.List[str]:
        return [member.content for member in ArrayType if member.status_id == status_id]
```

**Comment by lasso-codie** [comment]
I had a simpler but similar approach in mind, it would take the comfort though of using strings as a simple and quick alternative. It is a justified question though whether strings should be allowed in the first place. `get_state_array_names` is definitely error prone. Though we have tests covering this (they are in a company internal module). One Issue I still have with Enum is generating docs with sphinx containing the enum members. I was using `enum.Enum` just in `FilterType` for now since it has almost no members.

I like the recommendation and the code. The changes would break the API, so we will need to consider this thoroughly. Good Job!

**Comment by CamelCMA** [comment]
Hello, thanks for sharing us your thought. This project is fantastic! I believe it will be the tool to help us bridge the gap between traditional CAE and ML/AI.
